image:
  repository: docker.io/bizzkpm/taperecorder
  tag: "sha-5363c87"
  pullPolicy: IfNotPresent

env:
  PROJECT_ROOT: /app
  DATA_ROOT: /app/data
  TZ: Asia/Kolkata
  DUCKDB_MEMORY_LIMIT: "2GB"
  DUCKDB_THREADS: "2"
  UPSTOX_API_ACCESS_TOKEN: "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI3QkFYVDYiLCJqdGkiOiI2OTYzNTJjOTczOGU1NDNmMDIwYmNiOTUiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzY4MTE2OTM3LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NjgxNjg4MDB9.z2oCE8qKSWpw1II4G3P8WlyUxdmMLpDj2ZFF-fLC-NY"
  DO_S3_ENDPOINT_URL: "https://index-bucket.sgp1.digitaloceanspaces.com"
  DO_S3_REGION: "sgp1"
  DO_S3_BUCKET_NAME: "index-bucket"
  DO_S3_ACCESS_KEY_ID: "DO00HTRKUMPEG449UQQF"
  DO_S3_SECRET_ACCESS_KEY: "ylqc648Tf6pIyx+VAGQYYqfLJk6ck7sD8Z4tdZPjRk0"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"

  limits:
    cpu: "2"
    memory: "3Gi"

pvc:
  enabled: true
  size: 3Gi
