image:
  repository: docker.io/bizzkpm/taperecorder
  tag: latest
  pullPolicy: IfNotPresent

env:
  PROJECT_ROOT: /app
  DATA_ROOT: /app/data
  TZ: Asia/Kolkata
  DUCKDB_MEMORY_LIMIT: "2GB"
  DUCKDB_THREADS: "2"
  UPSTOX_API_ACCESS_TOKEN: "xxx"
  DO_S3_ENDPOINT_URL: "https://index-parquet.sgp1.digitaloceanspaces.com"
  DO_S3_REGION: "sgp1"
  DO_S3_BUCKET_NAME: "index-parquet"
  DO_S3_ACCESS_KEY_ID: "DO00HTRKUMPEG449UQQF"
  DO_S3_SECRET_ACCESS_KEY: "ylqc648Tf6pIyx+VAGQYYqfLJk6ck7sD8Z4tdZPjRk0"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"

  limits:
    cpu: "2"
    memory: "3Gi"

pvc:
  enabled: true
  size: 3Gi
